const INITIAL = 'INITIAL';
const ADD = 'ADD';
const EDIT = 'EDIT';
const SHOW = 'SHOW';
const REMOVE = 'REMOVE';
const FETCH_USER_DATA = 'FETCH_USER_DATA';
const FETCH_WORKS = 'FETCH_WORKS';
const INPUT_ID = 'INPUT_ID';
const INPUT_PASSWORD = 'INPUT_PASSWORD';
const INPUT_RE_PASSWORD = 'INPUT_RE_PASSWORD';
const INPUT_NAME = 'INPUT_NAME';
const LOADING_STATE = 'LOADING_STATE';
const CORRECT_STATE = 'CORRECT_STATE';
const INPUT_CHANGE = 'INPUT_CHANGE';
const FILTER_CHANGE = 'FILTER_CHANGE';
const FETCH_CURRENT_DATA = 'FETCH_CURRENT_DATA';
const SHOW_WORK = 'SHOW_WORK';
const EDIT_USER = 'EDIT_USER';
export {
  SHOW_WORK,
  INITIAL,
  ADD,
  EDIT,
  REMOVE,
  SHOW,
  INPUT_CHANGE,
  FILTER_CHANGE,
  FETCH_USER_DATA,
  FETCH_WORKS,
  INPUT_ID,
  INPUT_PASSWORD,
  INPUT_RE_PASSWORD,
  INPUT_NAME,
  LOADING_STATE,
  CORRECT_STATE,
  FETCH_CURRENT_DATA,
  EDIT_USER,
};
