const INITIAL = 'INITIAL';
const ADD = 'ADD';
const EDIT = 'EDIT';
const SHOW = 'SHOW';
const REMOVE = 'REMOVE';
const FETCH_USER_DATA = 'FETCH_USER_DATA';
const FETCH_WORKS = 'FETCH_WORKS';
const INPUT_ID = 'INPUT_ID';
const INPUT_PASSWORD = 'INPUT_PASSWORD';
const INPUT_RE_PASSWORD = 'INPUT_RE_PASSWORD';
const INPUT_NAME = 'INPUT_NAME';
const LOADING_STATE = 'LOADING_STATE';
const CORRECT_STATE = 'CORRECT_STATE';

export {
  INITIAL,
  ADD,
  EDIT,
  REMOVE,
  SHOW,
  FETCH_USER_DATA,
  FETCH_WORKS,
  INPUT_ID,
  INPUT_PASSWORD,
  INPUT_RE_PASSWORD,
  INPUT_NAME,
  LOADING_STATE,
  CORRECT_STATE,
};
